-- MySQL Script generated by MySQL Workbench
-- Tue Oct  8 19:37:35 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bdkafka
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdkafka
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdkafka` DEFAULT CHARACTER SET utf8mb3 ;
USE `bdkafka` ;

-- -----------------------------------------------------
-- Table `bdkafka`.`ordendedespacho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdkafka`.`ordendedespacho` (
  `idOrdenDeDespacho` INT NOT NULL AUTO_INCREMENT,
  `fechaEstimada` BIGINT NULL DEFAULT NULL,
  `ordenDeCompra` INT NOT NULL,
  PRIMARY KEY (`idOrdenDeDespacho`),
  INDEX `fk_ordendedespacho_ordendecompra1_idx` (`ordenDeCompra` ASC) VISIBLE,
  CONSTRAINT `fk_ordendedespacho_ordendecompra1`
    FOREIGN KEY (`ordenDeCompra`)
    REFERENCES `bdkafka`.`ordendecompra` (`idOrdenDeCompra`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bdkafka`.`ordendecompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdkafka`.`ordendecompra` (
  `idOrdenDeCompra` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL DEFAULT NULL,
  `tienda` VARCHAR(45) NULL DEFAULT NULL,
  `color` VARCHAR(45) NULL DEFAULT NULL,
  `talle` VARCHAR(45) NULL DEFAULT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `observaciones` VARCHAR(450) NULL DEFAULT NULL,
  `fechaSolicitud` BIGINT NULL DEFAULT NULL,
  `fechaRecepcion` BIGINT NULL DEFAULT NULL,
  `ordenDeDespacho` INT NULL DEFAULT NULL,
  `idOrdenAsociada` INT NOT NULL,
  PRIMARY KEY (`idOrdenDeCompra`),
  INDEX `fk_ordendecompra_ordendedespacho1_idx` (`ordenDeDespacho` ASC) VISIBLE,
  CONSTRAINT `fk_ordendecompra_ordendedespacho1`
    FOREIGN KEY (`ordenDeDespacho`)
    REFERENCES `bdkafka`.`ordendedespacho` (`idOrdenDeDespacho`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bdkafka`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdkafka`.`producto` (
  `codigo` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NULL DEFAULT NULL,
  `foto` VARCHAR(450) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bdkafka`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdkafka`.`stock` (
  `idStock` INT NOT NULL AUTO_INCREMENT,
  `talle` VARCHAR(45) NULL DEFAULT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `producto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStock`),
  INDEX `fk_stock_producto_idx` (`producto` ASC) VISIBLE,
  CONSTRAINT `fk_stock_producto`
    FOREIGN KEY (`producto`)
    REFERENCES `bdkafka`.`producto` (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
