INSERT INTO bdgrpc.tienda (direccion, ciudad, provincia, habilitado) VALUES ('CASACENTRAL', 'CASACENTRAL', 'CASACENTRAL', TRUE);
INSERT INTO bdgrpc.tienda (direccion, ciudad, provincia, habilitado) VALUES ('dirTienda1', 'ciuTienda1', 'provTienda1', TRUE);
INSERT INTO bdgrpc.usuario (usuario, password, nombre, apellido, habilitado, casaCentral, Tienda_idTienda) VALUES ( 'root', 'root', 'root', 'root', TRUE, TRUE, '1');
INSERT INTO bdgrpc.usuario (usuario, password, nombre, apellido, habilitado, casaCentral, Tienda_idTienda) VALUES ( 'user', '1234', 'nombre', 'apellido', TRUE, FALSE, '2');
INSERT INTO bdgrpc.producto (nombre, foto, color, codigo, habilitado) VALUES ('remera', 'https://dcdn.mitiendanube.com/stores/002/140/898/products/remera-azul1-f298c4d74417595e9616513267212895-640-0.jpg', 'azul', 'hAdEriTu9l', '1');
INSERT INTO bdgrpc.stock (cantidad, talle, tienda, producto) VALUES (0, "XXL", 1, 1);
INSERT INTO bdgrpc.stock (cantidad, talle, tienda, producto) VALUES (0, "XXL", 2, 1);
INSERT INTO bdgrpc.stock (cantidad, talle, tienda, producto) VALUES (0, "S", 1, 1);
INSERT INTO bdgrpc.stock (cantidad, talle, tienda, producto) VALUES (0, "S", 2, 1);
INSERT INTO bdgrpc.producto (nombre, foto, color, codigo, habilitado) VALUES ('remera estampada', 'https://www.tradicional13.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/t/r/tradicional_remera_hombre_negro.jpg', 'negra', 'hAdEriTu9l', '1');
INSERT INTO bdgrpc.stock (cantidad, talle, tienda, producto) VALUES (0, "XL", 1, 2);
INSERT INTO bdgrpc.stock (cantidad, talle, tienda, producto) VALUES (0, "XL", 2, 2);
INSERT INTO bdgrpc.stock (cantidad, talle, tienda, producto) VALUES (0, "L", 1, 2);
INSERT INTO bdgrpc.stock (cantidad, talle, tienda, producto) VALUES (0, "L", 2, 2);