# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: novedades.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'novedades.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fnovedades.proto\x12\tnovedades\"[\n\x0eNovedadGrpcDTO\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\r\n\x05talle\x18\x03 \x01(\t\x12\r\n\x05\x63olor\x18\x04 \x01(\t\x12\x0b\n\x03url\x18\x05 \x01(\t\"J\n\x15\x41gregarNovedadRequest\x12\x31\n\x0enovedadGrpcDTO\x18\x01 \x01(\x0b\x32\x19.novedades.NovedadGrpcDTO\"(\n\x16\x41gregarNovedadResponse\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t\"(\n\x16\x45liminarNovedadRequest\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t\")\n\x17\x45liminarNovedadResponse\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t\";\n\x0bNovedadList\x12,\n\tnovedades\x18\x01 \x03(\x0b\x32\x19.novedades.NovedadGrpcDTO\"\x1f\n\x1dTraerTodasLasNovedadesRequest\"M\n\x1eTraerTodasLasNovedadesResponse\x12+\n\x0bnovedadList\x18\x01 \x01(\x0b\x32\x16.novedades.NovedadList2\xb1\x02\n\tNovedades\x12W\n\x0e\x41gregarNovedad\x12 .novedades.AgregarNovedadRequest\x1a!.novedades.AgregarNovedadResponse\"\x00\x12Z\n\x0f\x45liminarNovedad\x12!.novedades.EliminarNovedadRequest\x1a\".novedades.EliminarNovedadResponse\"\x00\x12o\n\x16TraerTodasLasNovedades\x12(.novedades.TraerTodasLasNovedadesRequest\x1a).novedades.TraerTodasLasNovedadesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'novedades_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOVEDADGRPCDTO']._serialized_start=30
  _globals['_NOVEDADGRPCDTO']._serialized_end=121
  _globals['_AGREGARNOVEDADREQUEST']._serialized_start=123
  _globals['_AGREGARNOVEDADREQUEST']._serialized_end=197
  _globals['_AGREGARNOVEDADRESPONSE']._serialized_start=199
  _globals['_AGREGARNOVEDADRESPONSE']._serialized_end=239
  _globals['_ELIMINARNOVEDADREQUEST']._serialized_start=241
  _globals['_ELIMINARNOVEDADREQUEST']._serialized_end=281
  _globals['_ELIMINARNOVEDADRESPONSE']._serialized_start=283
  _globals['_ELIMINARNOVEDADRESPONSE']._serialized_end=324
  _globals['_NOVEDADLIST']._serialized_start=326
  _globals['_NOVEDADLIST']._serialized_end=385
  _globals['_TRAERTODASLASNOVEDADESREQUEST']._serialized_start=387
  _globals['_TRAERTODASLASNOVEDADESREQUEST']._serialized_end=418
  _globals['_TRAERTODASLASNOVEDADESRESPONSE']._serialized_start=420
  _globals['_TRAERTODASLASNOVEDADESRESPONSE']._serialized_end=497
  _globals['_NOVEDADES']._serialized_start=500
  _globals['_NOVEDADES']._serialized_end=805
# @@protoc_insertion_point(module_scope)
