# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import novedades_pb2 as novedades__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in novedades_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NovedadesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AgregarNovedad = channel.unary_unary(
                '/novedades.Novedades/AgregarNovedad',
                request_serializer=novedades__pb2.AgregarNovedadRequest.SerializeToString,
                response_deserializer=novedades__pb2.AgregarNovedadResponse.FromString,
                _registered_method=True)
        self.EliminarNovedad = channel.unary_unary(
                '/novedades.Novedades/EliminarNovedad',
                request_serializer=novedades__pb2.EliminarNovedadRequest.SerializeToString,
                response_deserializer=novedades__pb2.EliminarNovedadResponse.FromString,
                _registered_method=True)
        self.TraerTodasLasNovedades = channel.unary_unary(
                '/novedades.Novedades/TraerTodasLasNovedades',
                request_serializer=novedades__pb2.TraerTodasLasNovedadesRequest.SerializeToString,
                response_deserializer=novedades__pb2.TraerTodasLasNovedadesResponse.FromString,
                _registered_method=True)


class NovedadesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AgregarNovedad(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EliminarNovedad(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TraerTodasLasNovedades(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NovedadesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AgregarNovedad': grpc.unary_unary_rpc_method_handler(
                    servicer.AgregarNovedad,
                    request_deserializer=novedades__pb2.AgregarNovedadRequest.FromString,
                    response_serializer=novedades__pb2.AgregarNovedadResponse.SerializeToString,
            ),
            'EliminarNovedad': grpc.unary_unary_rpc_method_handler(
                    servicer.EliminarNovedad,
                    request_deserializer=novedades__pb2.EliminarNovedadRequest.FromString,
                    response_serializer=novedades__pb2.EliminarNovedadResponse.SerializeToString,
            ),
            'TraerTodasLasNovedades': grpc.unary_unary_rpc_method_handler(
                    servicer.TraerTodasLasNovedades,
                    request_deserializer=novedades__pb2.TraerTodasLasNovedadesRequest.FromString,
                    response_serializer=novedades__pb2.TraerTodasLasNovedadesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'novedades.Novedades', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('novedades.Novedades', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Novedades(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AgregarNovedad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/novedades.Novedades/AgregarNovedad',
            novedades__pb2.AgregarNovedadRequest.SerializeToString,
            novedades__pb2.AgregarNovedadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EliminarNovedad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/novedades.Novedades/EliminarNovedad',
            novedades__pb2.EliminarNovedadRequest.SerializeToString,
            novedades__pb2.EliminarNovedadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TraerTodasLasNovedades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/novedades.Novedades/TraerTodasLasNovedades',
            novedades__pb2.TraerTodasLasNovedadesRequest.SerializeToString,
            novedades__pb2.TraerTodasLasNovedadesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
