# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ordenCompra.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'ordenCompra.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ordenCompra.proto\x12\x0bordenCompra\"\xc0\x01\n\x12OrdenCompraGrpcDTO\x12\x17\n\x0fidOrdenDeCompra\x18\x01 \x01(\x03\x12\x0f\n\x07idStock\x18\x02 \x01(\x03\x12\x10\n\x08\x63\x61ntidad\x18\x03 \x01(\t\x12\x0e\n\x06\x65stado\x18\x04 \x01(\t\x12\x15\n\robservaciones\x18\x05 \x01(\t\x12\x16\n\x0e\x66\x65\x63haSolicitud\x18\x06 \x01(\x03\x12\x16\n\x0e\x66\x65\x63haRecepcion\x18\x07 \x01(\x03\x12\x17\n\x0fordenDeDespacho\x18\x08 \x01(\x03\"X\n\x19\x41gregarOrdenCompraRequest\x12;\n\x12ordenCompraGrpcDTO\x18\x01 \x01(\x0b\x32\x1f.ordenCompra.OrdenCompraGrpcDTO\"5\n\x1a\x41gregarOrdenCompraResponse\x12\x17\n\x0fidOrdenDeCompra\x18\x01 \x01(\x03\"C\n\x0fOrdenCompraList\x12\x30\n\x07ordenes\x18\x01 \x03(\x0b\x32\x1f.ordenCompra.OrdenCompraGrpcDTO\"Z\n\x1bModificarOrdenCompraRequest\x12;\n\x12ordenCompraGrpcDTO\x18\x01 \x01(\x0b\x32\x1f.ordenCompra.OrdenCompraGrpcDTO\"7\n\x1cModificarOrdenCompraResponse\x12\x17\n\x0fidOrdenDeCompra\x18\x01 \x01(\x03\"5\n\x1a\x45liminarOrdenCompraRequest\x12\x17\n\x0fidOrdenDeCompra\x18\x01 \x01(\x03\"6\n\x1b\x45liminarOrdenCompraResponse\x12\x17\n\x0fidOrdenDeCompra\x18\x01 \x01(\x03\"/\n\x1bTraerTodasLasOrdenesRequest\x12\x10\n\x08idTienda\x18\x01 \x01(\x03\"O\n\x1cTraerTodasLasOrdenesResponse\x12/\n\tordenList\x18\x01 \x01(\x0b\x32\x1c.ordenCompra.OrdenCompraList2\xae\x03\n\x0bOrdenCompra\x12\x61\n\x0c\x41gregarOrden\x12&.ordenCompra.AgregarOrdenCompraRequest\x1a\'.ordenCompra.AgregarOrdenCompraResponse\"\x00\x12g\n\x0eModificarOrden\x12(.ordenCompra.ModificarOrdenCompraRequest\x1a).ordenCompra.ModificarOrdenCompraResponse\"\x00\x12\x64\n\rEliminarOrden\x12\'.ordenCompra.EliminarOrdenCompraRequest\x1a(.ordenCompra.EliminarOrdenCompraResponse\"\x00\x12m\n\x14TraerTodasLasOrdenes\x12(.ordenCompra.TraerTodasLasOrdenesRequest\x1a).ordenCompra.TraerTodasLasOrdenesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ordenCompra_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDENCOMPRAGRPCDTO']._serialized_start=35
  _globals['_ORDENCOMPRAGRPCDTO']._serialized_end=227
  _globals['_AGREGARORDENCOMPRAREQUEST']._serialized_start=229
  _globals['_AGREGARORDENCOMPRAREQUEST']._serialized_end=317
  _globals['_AGREGARORDENCOMPRARESPONSE']._serialized_start=319
  _globals['_AGREGARORDENCOMPRARESPONSE']._serialized_end=372
  _globals['_ORDENCOMPRALIST']._serialized_start=374
  _globals['_ORDENCOMPRALIST']._serialized_end=441
  _globals['_MODIFICARORDENCOMPRAREQUEST']._serialized_start=443
  _globals['_MODIFICARORDENCOMPRAREQUEST']._serialized_end=533
  _globals['_MODIFICARORDENCOMPRARESPONSE']._serialized_start=535
  _globals['_MODIFICARORDENCOMPRARESPONSE']._serialized_end=590
  _globals['_ELIMINARORDENCOMPRAREQUEST']._serialized_start=592
  _globals['_ELIMINARORDENCOMPRAREQUEST']._serialized_end=645
  _globals['_ELIMINARORDENCOMPRARESPONSE']._serialized_start=647
  _globals['_ELIMINARORDENCOMPRARESPONSE']._serialized_end=701
  _globals['_TRAERTODASLASORDENESREQUEST']._serialized_start=703
  _globals['_TRAERTODASLASORDENESREQUEST']._serialized_end=750
  _globals['_TRAERTODASLASORDENESRESPONSE']._serialized_start=752
  _globals['_TRAERTODASLASORDENESRESPONSE']._serialized_end=831
  _globals['_ORDENCOMPRA']._serialized_start=834
  _globals['_ORDENCOMPRA']._serialized_end=1264
# @@protoc_insertion_point(module_scope)
