# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ordenCompra_pb2 as ordenCompra__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ordenCompra_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrdenCompraStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AgregarOrden = channel.unary_unary(
                '/ordenCompra.OrdenCompra/AgregarOrden',
                request_serializer=ordenCompra__pb2.AgregarOrdenCompraRequest.SerializeToString,
                response_deserializer=ordenCompra__pb2.AgregarOrdenCompraResponse.FromString,
                _registered_method=True)
        self.ModificarOrden = channel.unary_unary(
                '/ordenCompra.OrdenCompra/ModificarOrden',
                request_serializer=ordenCompra__pb2.ModificarOrdenCompraRequest.SerializeToString,
                response_deserializer=ordenCompra__pb2.ModificarOrdenCompraResponse.FromString,
                _registered_method=True)
        self.EliminarOrden = channel.unary_unary(
                '/ordenCompra.OrdenCompra/EliminarOrden',
                request_serializer=ordenCompra__pb2.EliminarOrdenCompraRequest.SerializeToString,
                response_deserializer=ordenCompra__pb2.EliminarOrdenCompraResponse.FromString,
                _registered_method=True)
        self.TraerTodasLasOrdenes = channel.unary_unary(
                '/ordenCompra.OrdenCompra/TraerTodasLasOrdenes',
                request_serializer=ordenCompra__pb2.TraerTodasLasOrdenesRequest.SerializeToString,
                response_deserializer=ordenCompra__pb2.TraerTodasLasOrdenesResponse.FromString,
                _registered_method=True)


class OrdenCompraServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AgregarOrden(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModificarOrden(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EliminarOrden(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TraerTodasLasOrdenes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrdenCompraServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AgregarOrden': grpc.unary_unary_rpc_method_handler(
                    servicer.AgregarOrden,
                    request_deserializer=ordenCompra__pb2.AgregarOrdenCompraRequest.FromString,
                    response_serializer=ordenCompra__pb2.AgregarOrdenCompraResponse.SerializeToString,
            ),
            'ModificarOrden': grpc.unary_unary_rpc_method_handler(
                    servicer.ModificarOrden,
                    request_deserializer=ordenCompra__pb2.ModificarOrdenCompraRequest.FromString,
                    response_serializer=ordenCompra__pb2.ModificarOrdenCompraResponse.SerializeToString,
            ),
            'EliminarOrden': grpc.unary_unary_rpc_method_handler(
                    servicer.EliminarOrden,
                    request_deserializer=ordenCompra__pb2.EliminarOrdenCompraRequest.FromString,
                    response_serializer=ordenCompra__pb2.EliminarOrdenCompraResponse.SerializeToString,
            ),
            'TraerTodasLasOrdenes': grpc.unary_unary_rpc_method_handler(
                    servicer.TraerTodasLasOrdenes,
                    request_deserializer=ordenCompra__pb2.TraerTodasLasOrdenesRequest.FromString,
                    response_serializer=ordenCompra__pb2.TraerTodasLasOrdenesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ordenCompra.OrdenCompra', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ordenCompra.OrdenCompra', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrdenCompra(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AgregarOrden(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ordenCompra.OrdenCompra/AgregarOrden',
            ordenCompra__pb2.AgregarOrdenCompraRequest.SerializeToString,
            ordenCompra__pb2.AgregarOrdenCompraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModificarOrden(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ordenCompra.OrdenCompra/ModificarOrden',
            ordenCompra__pb2.ModificarOrdenCompraRequest.SerializeToString,
            ordenCompra__pb2.ModificarOrdenCompraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EliminarOrden(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ordenCompra.OrdenCompra/EliminarOrden',
            ordenCompra__pb2.EliminarOrdenCompraRequest.SerializeToString,
            ordenCompra__pb2.EliminarOrdenCompraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TraerTodasLasOrdenes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ordenCompra.OrdenCompra/TraerTodasLasOrdenes',
            ordenCompra__pb2.TraerTodasLasOrdenesRequest.SerializeToString,
            ordenCompra__pb2.TraerTodasLasOrdenesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
