# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import usuario_pb2 as usuario__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in usuario_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UsuarioStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AgregarUsuario = channel.unary_unary(
                '/testgrpc.Usuario/AgregarUsuario',
                request_serializer=usuario__pb2.AgregarUsuarioRequest.SerializeToString,
                response_deserializer=usuario__pb2.AgregarUsuarioResponse.FromString,
                _registered_method=True)
        self.TraerTodosLosUsuarios = channel.unary_unary(
                '/testgrpc.Usuario/TraerTodosLosUsuarios',
                request_serializer=usuario__pb2.TraerTodosLosUsuariosRequest.SerializeToString,
                response_deserializer=usuario__pb2.TraerTodosLosUsuariosResponse.FromString,
                _registered_method=True)
        self.TraerTodosLosUsuariosPorNombre = channel.unary_unary(
                '/testgrpc.Usuario/TraerTodosLosUsuariosPorNombre',
                request_serializer=usuario__pb2.TraerTodosLosUsuariosPorNombreRequest.SerializeToString,
                response_deserializer=usuario__pb2.TraerTodosLosUsuariosPorNombreResponse.FromString,
                _registered_method=True)
        self.TraerUsuarioPorTienda = channel.unary_unary(
                '/testgrpc.Usuario/TraerUsuarioPorTienda',
                request_serializer=usuario__pb2.TraerUsuarioPorTiendaRequest.SerializeToString,
                response_deserializer=usuario__pb2.TraerUsuarioPorTiendaResponse.FromString,
                _registered_method=True)


class UsuarioServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AgregarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TraerTodosLosUsuarios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TraerTodosLosUsuariosPorNombre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TraerUsuarioPorTienda(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsuarioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AgregarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.AgregarUsuario,
                    request_deserializer=usuario__pb2.AgregarUsuarioRequest.FromString,
                    response_serializer=usuario__pb2.AgregarUsuarioResponse.SerializeToString,
            ),
            'TraerTodosLosUsuarios': grpc.unary_unary_rpc_method_handler(
                    servicer.TraerTodosLosUsuarios,
                    request_deserializer=usuario__pb2.TraerTodosLosUsuariosRequest.FromString,
                    response_serializer=usuario__pb2.TraerTodosLosUsuariosResponse.SerializeToString,
            ),
            'TraerTodosLosUsuariosPorNombre': grpc.unary_unary_rpc_method_handler(
                    servicer.TraerTodosLosUsuariosPorNombre,
                    request_deserializer=usuario__pb2.TraerTodosLosUsuariosPorNombreRequest.FromString,
                    response_serializer=usuario__pb2.TraerTodosLosUsuariosPorNombreResponse.SerializeToString,
            ),
            'TraerUsuarioPorTienda': grpc.unary_unary_rpc_method_handler(
                    servicer.TraerUsuarioPorTienda,
                    request_deserializer=usuario__pb2.TraerUsuarioPorTiendaRequest.FromString,
                    response_serializer=usuario__pb2.TraerUsuarioPorTiendaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'testgrpc.Usuario', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('testgrpc.Usuario', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Usuario(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AgregarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testgrpc.Usuario/AgregarUsuario',
            usuario__pb2.AgregarUsuarioRequest.SerializeToString,
            usuario__pb2.AgregarUsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TraerTodosLosUsuarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testgrpc.Usuario/TraerTodosLosUsuarios',
            usuario__pb2.TraerTodosLosUsuariosRequest.SerializeToString,
            usuario__pb2.TraerTodosLosUsuariosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TraerTodosLosUsuariosPorNombre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testgrpc.Usuario/TraerTodosLosUsuariosPorNombre',
            usuario__pb2.TraerTodosLosUsuariosPorNombreRequest.SerializeToString,
            usuario__pb2.TraerTodosLosUsuariosPorNombreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TraerUsuarioPorTienda(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testgrpc.Usuario/TraerUsuarioPorTienda',
            usuario__pb2.TraerUsuarioPorTiendaRequest.SerializeToString,
            usuario__pb2.TraerUsuarioPorTiendaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
